name: Test
on: [push]
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - name: Test
        run: npm test
